name: open_fridge

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [30]
      type: low_dim
  action:
    shape: [13]

env_runner:
  _target_: diffusion_policy_3d.env_runner.mshab_runner.MSHABRunner
  task_name: ${task_name}
  eval_episodes: 100
  output_dir: ./output
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  max_episode_steps: 200

dataset:
  _target_: diffusion_policy_3d.dataset.mshab_dataset.MSHABDataset
  zarr_path: /data/jh/extra/open_fridge_crop.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
